USE master
GO
CREATE DATABASE PBDSI

ON PRIMARY 
(

	NAME = 'PBDSI_data', FILENAME = 'C:\temp\proyectoInventario\PBDSI_data.mdf', SIZE = 10MB, MAXSIZE = UNLIMITED

)
LOG ON
(
	NAME = 'PBDSI_log', FILENAME = 'C:\temp\proyectoInventario\PBDSI_log.ldf', SIZE = 5MB, MAXSIZE = 2GB
)
GO
USE PBDSI

GO

CREATE TABLE [PRODUCTO]
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PRODUCTO NVARCHAR(50) NOT NULL,
	PRECIO          FLOAT(50) NOT NULL,
	FECHA_ELABORACION DATETIME,
	FECHA_VENCIMIENTO DATETIME,
	--PRIMARY KEY(ID)
)
CREATE TABLE CATEGORIA
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CATEGORIA NVARCHAR(50) NOT NULL,
	ID_PRODUCTO INT,
	--PRIMARY KEY(ID)
)

ALTER TABLE CATEGORIA
	WITH CHECK ADD CONSTRAINT FK_PRO_MARCA_CONCEPTO
	FOREIGN KEY (ID_CONCEPTO)
	REFERENCES [MERCADEO].[CONCEPTO](ID)
ON DELETE CASCADE;
SELECT * FROM GASTO;

CREATE TABLE INVENTARIO
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ENTRADA FLOAT(50) NOT NULL,
	SALIDA          FLOAT(50) NOT NULL,
	EXISTENCIAS   FLOAT(50),
	ID_PRODUCTO    INT ,
	--PRIMARY KEY(ID)
) 
ALTER TABLE INVENTARIO
	WITH CHECK ADD CONSTRAINT FK_PRODUCTO
	FOREIGN KEY (ID_PRODUCTO)
	REFERENCES INVENTARIO(ID)
ON DELETE CASCADE;

CREATE TABLE PROVEEDOR
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_DIRECCION VARCHAR(50) NOT NULL,
	DIRECCION     VARCHAR(50) NOT NULL,
	NOMBRE_VENDEDOR   VARCHAR(50),
	APELLIDO_VENDEDOR   VARCHAR(50),
	DIAS_VISITA    DATE,
	ID_PRODUCTO  INT,
	ID_COMPRA  INT,
	--PRIMARY KEY(ID)
)
ALTER TABLE PROVEEDOR
	WITH CHECK ADD CONSTRAINT FK_PROVEEDOR_PRODUCTO
	FOREIGN KEY (ID_PRODUCTO)
	REFERENCES PRODUCTO(ID)
ON DELETE CASCADE;
ALTER TABLE PROVEEDOR
	WITH CHECK ADD CONSTRAINT FK_PROVEEDOR_COMPRA
	FOREIGN KEY (ID_COMPRA)
	REFERENCES COMPRA(ID)
ON DELETE CASCADE;

CREATE TABLE COMPRA
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
	PRECIO_COSTO    FLOAT(50) NOT NULL,
	CANTIDAD   FLOAT(50),
	ID_INVENTARIO  INT,
	ID_PROVEEDOR  INT,
	--PRIMARY KEY(ID)
)
ALTER TABLE COMPRA
	WITH CHECK ADD CONSTRAINT FK_COMPRA_INVENTARIO
	FOREIGN KEY (ID_INVENTARIO)
	REFERENCES INVENTARIO(ID)
ON DELETE CASCADE;
ALTER TABLE COMPRA
	WITH CHECK ADD CONSTRAINT FK_COMPRA_INVENTARIO
	FOREIGN KEY (ID_INVENTARIO)
	REFERENCES INVENTARIO(ID)
ON DELETE CASCADE;
CREATE TABLE COMPRA_CONTADO
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
	NO_FACTURA   FLOAT(50) NOT NULL,
	CANTIDAD   FLOAT(50),
	ID_COMPRA  INT,
	--PRIMARY KEY(ID)
)
CREATE TABLE COMPRA_CREDITO
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
	PRECIO_COSTO    FLOAT(50) NOT NULL,
	CANTIDAD   FLOAT(50),
	FECHA_COMPRA DATETIME,
	FECHA_PAGO DATETIME,
	ID_COMPRA  INT,
	--PRIMARY KEY(ID)
)
ALTER TABLE COMPRA_CONTADO
	WITH CHECK ADD CONSTRAINT FK_COMPRA_CONTADO_INVENTARIO
	FOREIGN KEY (ID_COMPRA)
	REFERENCES COMPRA(ID)
ON DELETE CASCADE;
ALTER TABLE COMPRA_CREDITO
	WITH CHECK ADD CONSTRAINT FK_COMPRA_CREDOTO_INVENTARIO
	FOREIGN KEY (ID_COMPRA)
	REFERENCES COMPRA(ID)
ON DELETE CASCADE;
CREATE TABLE GASTO
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
	CANTIDAD  FLOAT(50) NOT NULL,
	FECHA_GASTO DATETIME,
	ID_INVENTARIO  INT,
	--PRIMARY KEY(ID)
)
CREATE TABLE GASTO_PERSONALES
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FECHA_GASTO DATETIME,
	DESCRICCION_GASTO VARCHAR(50),
	MONTO FLOAT(50),
	NOMBRE_USUARIO VARCHAR(50),
	ID_INVENTARIO  INT,
	ID_GASTO  INT,
	--PRIMARY KEY(ID)
)
CREATE TABLE GASTO_PUBLICOS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LUZ_ELECTRICA VARCHAR(50) NOT NULL,
	IMPUESTO_MUNICIPAL FLOAT(50) NOT NULL,
	ID_INVENTARIO  INT,
	ID_GASTO INT,
	--PRIMARY KEY(ID)
)
ALTER TABLE GASTO
	WITH CHECK ADD CONSTRAINT FK_GASTO_INVENTARIO
	FOREIGN KEY (ID_INVENTARIO)
	REFERENCES INVENTARIO(ID)
ON DELETE CASCADE;



ALTER TABLE GASTO_PUBLICOS
	WITH CHECK ADD CONSTRAINT FK_GASTO_PUBLICO_INVENTARIO
	FOREIGN KEY (ID_INVENTARIO)
	REFERENCES INVENTARIO(ID)
ON DELETE CASCADE;

ALTER TABLE GASTO_PERSONALES
	WITH CHECK ADD CONSTRAINT FK_GASTO_PERSONAL_INVENTARIO
	FOREIGN KEY (ID_INVENTARIO)
	REFERENCES INVENTARIO(ID)
ON DELETE CASCADE;
DROP TABLE PEDIDO;
SELECT * FROM USUARIO;

CREATE TABLE CLIENTES
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_CLIENTE VARCHAR(50),
	APELLIDO_CLIENTE VARCHAR(50),
	tELEFONO_CLIENTE VARCHAR(50),
	OBSERVACIONES VARCHAR(50),
	ID_VENTAS  INT,
	--PRIMARY KEY(ID)
)
CREATE TABLE USUARIO
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_USUARIO VARCHAR(50),
	APELLIDO_USUARIO VARCHAR(50),
	EMAIL VARCHAR(50),
	OBSERVACIONES VARCHAR(50),
	ID_INVENTARIO  INT,
	--PRIMARY KEY(ID)
)
ALTER TABLE CLIENTES
	WITH CHECK ADD CONSTRAINT FK_CLIENTES_VENTAS
	FOREIGN KEY (ID_VENTAS)
	REFERENCES VENTAS(ID)
ON DELETE CASCADE;

ALTER TABLE USUARIO
	WITH CHECK ADD CONSTRAINT FK_USUARIO_INVENTARIO
	FOREIGN KEY (ID_INVENTARIO)
	REFERENCES INVENTARIO(ID)
ON DELETE CASCADE;

CREATE TABLE TELEFONO_PROVEEDOR
(
 ID INT IDENTITY(1,1) PRIMARY KEY,
 TEL_EMPRESA VARCHAR(50),
 TEL_VENDEDOR VARCHAR(50),
 ID_PROVEEDOR INT,
)
ALTER TABLE TELEFONO_PROVEEDOR
	WITH CHECK ADD CONSTRAINT FK_TELEFONO_PROVEEDOR
	FOREIGN KEY (ID_PROVEEDOR)
	REFERENCES PROVEEDOR(ID)
ON DELETE CASCADE;

CREATE TABLE VENTAS
(
 ID INT IDENTITY(1,1) PRIMARY KEY,
 NOMBRE_PRODUCTO VARCHAR(50),
 PRECIO_VENTA FLOAT(50),
 CANTIDAD FLOAT(50),
 ID_INVENTARIO INT,
 ID_PRODUCTO INT,
 --PRIMARY KEY(ID)
)

CREATE TABLE PEDIDOS
(
 ID INT IDENTITY(1,1) PRIMARY KEY,
 FECHA_PEDIDO DATE,
 FECHA_ENTREGA DATE,
 ID_COMPRA INT,
 ID_PROVEEDOR INT,
 --PRIMARY KEY(ID)
)
ALTER TABLE VENTAS
	WITH CHECK ADD CONSTRAINT FK_VENTAS_INVENTARIO
	FOREIGN KEY (ID_INVENTARIO)
	REFERENCES INVENTARIO(ID)
ON DELETE CASCADE;
ALTER TABLE VENTAS
	WITH CHECK ADD CONSTRAINT FK_VENTAS_PRODUCTO
	FOREIGN KEY (ID_PRODUCTO)
	REFERENCES PRODUCTO(ID)
ON DELETE CASCADE;
ALTER TABLE PEDIDOs
	WITH CHECK ADD CONSTRAINT FK_PEDIDO_COMPRA
	FOREIGN KEY (ID_COMPRA)
	REFERENCES COMPRA(ID)
ON DELETE CASCADE;