CREATE PROCEDURE SP_PRUEBA1
AS 
PRINT 'HOLA MUNDO'

EXECUTE SP_PRUEBA1


CREATE PROC SP_CONSULTA AS
SELECT * FROM PRODUCTO
WHERE ID= 4
EXECUTE SP_CONSULTA

CREATE PROC SP_RESTAR_EXISTENCIA
@ID AS VARCHAR(4),
@PRECIO AS INT
AS 
UPDATE PRODUCTO SET EXISTENCIA = EXISTENCIA - @PRECIO
WHERE ID-@ID

EXEC SP_RESTAR_EXISTENCIA '4',10



